### ISSUE TITLE
Change type of keys to []interface{}

### ISSUE THREAD

**Issue by mastertinner** [nicksrandall/dataloader#30] opened 2017-12-04 20:42 UTC
Why does `keys` have to be a `[]string`? I am working with https://labix.org/mgo where all IDs are of type `bson.ObjectId`. This makes using `dataloader` somewhat impractical because I have to convert all `bson.ObjectId`s into `string`s before piping them into the `Load` function of `dataloader`. In there, I have to convert them back to `bson.ObjectId`s to execute the MongoDB queries. If the `Load` function would except the keys as `[]interface{}` instead of `[]string`, that would make my life a lot easier because I could directly pipe the `bson.ObjectId`s into it.

The `context.Context` package works the same way. There, a key can also be `interface{}`.

**Comment by mastertinner** [comment] 2017-12-04 21:53
I just saw that this was already discussed in #23. Sorry for the duplicate! Nevertheless, it gives no reason for being closed and I saw that they had similar discussions on https://github.com/facebook/dataloader/pull/15 so I thought I'd bring it up again.

**Comment by tonyghita** [comment] 2017-12-04 22:59
I closed the issue because I decided to just use strings rather than force users to use `interface{}`. 

If a similar change was merged into github.com/facebook/dataloader we should probably consider something similar here.

**Comment by nicksrandall** [comment] 2017-12-05 00:02
Thanks for bringing this up @mastertinner. It appears that the spec has changed since I built this library so I'm open to this change. I'll work on it tomorrow and release a new version.

**Comment by nicksrandall** [comment] 2017-12-05 04:14
@mastertinner @tonyghita What do you think of this: https://github.com/nicksrandall/dataloader/compare/v4

If you are ok with the change, I'll make the v4 branch the main branch.

**Comment by tonyghita** [comment] 2017-12-05 17:01
@nicksrandall thanks! I think that looks good :)

**Comment by mastertinner** [comment] 2017-12-05 18:27
Absolutely fantastic! Thanks so much, @nicksrandall!

**Comment by nicksrandall** [comment] 2017-12-05 23:59
This change has been merged in.  @tonyghita I also tagged the release.

**Closed** 2017-12-05 23:59 UTC

**Comment by mastertinner** [comment] 2017-12-06 00:11
Thanks, @tonyghita and @nicksrandall! You guys have been awesome with replying to my requests!

**Comment by tonyghita** [comment] 2017-12-13 05:31
Just wanted to share my experience upgrading from `v2` to `v4.1.0` in my toy project.

https://github.com/tonyghita/graphql-go-example/commit/c0369fd0bf7a2832feff53e672b58e43a7c4c642

After the upgrade, there is a lot more copying ([due to []interface{}](https://github.com/golang/go/wiki/InterfaceSlice)), but I _think_ it should be cheap enough to be acceptable.

**Comment by nicksrandall** [comment] 2017-12-13 06:19
@tonyghita I’m also worried about this as I have had a similar experience. What if instead of allowing empty interface, we required a specific interface. Something like:

```go
type Key interface{
  String() string
  Value() interface{}
}
```

Do you think that would help?

**Comment by tonyghita** [comment] 2017-12-13 06:28
Hmm.... I'm not exactly sure what the best path forward looks like yet. 

In my work use-cases, we have way more dataloaders with string keys than those with composite keys. For now, we just create composite string keys with some kind of separator like `;` for those loaders. This is a pretty brittle approach but generally it works because these cases are fairly limited.

I'll play around with some ideas and come back to this. In the meantime it might help if we write some benchmarks... I'll look into this (will help catch any perf regressions).
